function res=bgwi2bgwr(Z)
% bgwi2bgwr(Z)
%   conver a BGW process with immigration to 
%   BGW proces with random number of ancestors
%
%   The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead, 3 - immigrant)

%  04.2016, Amady Ba
%  amady.sba@gmail.com

 res = Z;
 for k = 1:size(Z,2)
     if Z(3,k) == 3
        res(2,k) = 0;
    else
        res(2,k) = res(2,Z(1,k))+1;
     end;
 end;
