function res=bp_count_popul(Z)
%  res=bp_count_polul(Z)
%    returns the population for the each generation 
%    of the process Z generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%
% use distinct.m

%  04.2016, Amady Ba
%  amady.sba@gmail.com

R = distinct(Z(2,:));
res = [];
for g = R
    res(g) = length(find(Z(2,:) == g & Z(3,:) ~= 2));
end;

