function res=bp_harris_est(Z)
% bp_harris_est(Z) 
%   returns the Harris Estimator for the process Z
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)


%  04.2016, Amady Ba
%  amady.sba@gmail.com

T = bp_count_popul(Z);
res = sum(T([2:length(T)]))/sum(T([1:length(T) - 1]));
