function res=bp_harris_est_mt(Z)
% bp_harris_est_mt(Z) 
%   returns the Harris Estimator for the processes Z
%   for more than one tree.
%
%    The process Z is generated by bp_gen_mt
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
%   Z(4,:) - tree number


%  04.2016, Amady Ba
%  amady.sba@gmail.com

if size(Z,1) < 4
    error('Wrong size of the input parameter Z. Try bp_haris_est!!!');
end;

Tr = distinct(Z(4,:));
if length(Tr) == 1 
    warning('There is only one tree. Better use bp_haris_est!!!');
end;

for t = Tr
    T = bp_count_popul(Z(1:3,find(Z(4,:) == t)));
    S_nom(t) = sum(T([2:length(T)]));
    S_den(t) = sum(T([1:length(T) - 1]));
end;

res = sum(S_nom)/sum(S_den);
