function res=bp_ind_dist(Z)
% bp_ind_dist(Z)
%   returns the individual distribution estimator
%   for the process Z
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)


%  04.2016, Amady Ba
%  amady.sba@gmail.com

Ch = bp_count_childs(Z);
T = bp_count_popul(Z);
S = sum(T([1:length(T) - 1]));
for k = 1:length(Ch)
    res(k) = Ch(k)/S;
end;
