function l=bp_immigr_dy_est(Z, m)
% bp_immigr_dy_est(Z,m) 
%   returns the estimates of the immigration mean for the process Z
%
%   The output is
%   l - the immigrantion mean, according to Dion & Yanev
%       l is matrix, l(n,t) = lambda_t(n)
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead, 3 - immigrant)
%   m - the offspting mean

%  04.2016, Amady Ba
%  amady.sba@gmail.com

T = max(Z(2,:)); %number of generations

l=[];
for n = 1:T
    Im = find( Z(3,:) == 3 & Z(2,:) <= n);
    R= [];
    for im = Im
        R = [R extract_sub_tree(Z,im)];
    end;
    
    if ~isempty(R)
        l(n,1) = ( length(find(R(2,:) == 0 & R(3,:) == 3 )) )/n;
        for t = 1:T-n
            l(n,t+1) = ( length(find(R(2,:) == t & R(3,:) ~= 2 & R(3,:) ~= 3 )) )/(n*m^(t));
        end;
    else
        l(n,1) = 0;
    end;
end;
