function res=bp_ind_var(Z,m)
% bp_ind_var(Z)
%   returns the individual variance estimator
%   for the process Z
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)
% 
%   m is the theoretical mean of the distribution
%     by default is the Harris estimator

%  04.2016, Amady Ba
%  amady.sba@gmail.com

if nargin == 1
    m = bp_harris_est(Z);
end;

Ind_D = bp_ind_dist(Z);

res = sum((((1:length(Ind_D)) - m).^2)*Ind_D');

