function res=bp_ln_est(Z)
% bp_ln_est(Z) 
%   returns the Lotka-Nagaev Estimator for the process Z
%
%    The process Z is generated by gen_bp
%   Z(1,:) - vector of parent pointers
%   Z(2,:) - generation
%   Z(3,:) - type ot particle (1 - live, 2 - dead)


%  04.2016, Amady Ba
%  amady.sba@gmail.com

T = bp_count_popul(Z);

if T(length(T)-1)==0
    res=1;
else
    res=T(length(T))/T(length(T)-1);
end;
